export const OPERAND_INPUT = "OPERAND_INPUT";
export const OPERATION_INPUT = "OPERATION_INPUT";
export const TOGGLE_NEGATION = "TOGGLE_NEGATION";

export const CLEAR_ENTRY = "CLEAR_ENTRY";
export const ALL_CLEAR = "ALL_CLEAR";

export const CALCULATE_RESULT = "CALCULATE_RESULT";
